services:
    postgres:
        image: postgres:18-alpine
        container_name: cafe-postgres-dev
        # restart: always
        environment:
            POSTGRES_USER: cafe_admin
            POSTGRES_PASSWORD: cafe_secure_pass
            POSTGRES_DB: cafe_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data_dev:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U cafe_admin -d cafe_db"]
            interval: 5s
            timeout: 5s
            retries: 5

    web-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: cafe-services-dev
        # restart: always
        env_file: .env.development
        ports:
            - "3001:3000"
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - .:/app:consistent
            - /app/node_modules
            - /app/.next
            - uploads_data_dev:/app/public/uploads
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
            - DATABASE_URL=postgresql://cafe_admin:cafe_secure_pass@postgres:5432/cafe_db?schema=public
            - DEFAULT_USERNAME=admin
            - DEFAULT_USER_PASSWORD=admin123
            - DEFAULT_HASH_METHOD=sha256
            - DEFAULT_PASSWORD_SALT=KFLSjflespJ;F93fuir3kmwoFP3JEWFP9urwlmso3

volumes:
    postgres_data_dev:
        driver: local
    uploads_data_dev:
        driver: local
